enum Ctrl {
    UP = 'w',
    UPRIGHT = 'e',
    RIGHT = 'd',
    DOWNRIGHT = 'c',
    DOWN = 'x',
    DOWNLEFT = 'z',
    LEFT = 'a',
    UPLEFT = 'q',
    IDLE = 's',
    ACTIVATE = 'f',
    USE0 = 'y',
    USE1 = 'u',
    USE2 = 'i',
    USE3 = 'o',
    USE4 = 'p',
};
