enum Ctrl {
    UP = 'w',
    UPRIGHT = 'e',
    RIGHT = 'd',
    DOWNRIGHT = 'c',
    DOWN = 'x',
    DOWNLEFT = 'z',
    LEFT = 'a',
    UPLEFT = 'q',
    IDLE = 's',
    ACTIVATE = 'f',
    USE0 = 'p',
    USE1 = '[',
    USE2 = ']',
    USE3 = 'l',
    USE4 = ';',
    USE5 = '\'',
};
